services:
  app:
    image: sergiohscl/weather-api:latest
    container_name: weather-app
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      PYTHONUNBUFFERED: "1"

    env_file:
      - ${ENV_FILE:-.env}

    volumes:
      - sqlite_data:/home/weather/data
      - uploads_data:/home/weather/uploads

    depends_on:
      - rabbitmq
      - redis

    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "weather.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]

  celery_worker:
    image: sergiohscl/weather-api:latest
    container_name: weather-celery-worker
    restart: unless-stopped

    environment:
      PYTHONUNBUFFERED: "1"

    env_file:
      - ${ENV_FILE:-.env}

    volumes:
      - sqlite_data:/home/weather/data
      - uploads_data:/home/weather/uploads

    depends_on:
      - rabbitmq
      - redis

    command:
      [
        "/home/weather/.venv/bin/celery",
        "-A",
        "weather.tasks.weather.celery_app:celery_app",
        "worker",
        "--loglevel=info"
      ]

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: weather-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: weather-redis
    restart: unless-stopped

volumes:
  sqlite_data:
  uploads_data:
  redis_data: