version: "3.8"

services:
  app:
    image: sergiohscl/weather-api:latest
    container_name: weather-app
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      PYTHONUNBUFFERED: "1"

    env_file:
      - .env

    volumes:
      - sqlite_data:/home/weather/weather.db
      - uploads_data:/home/weather/uploads

    command:
      [
        "poetry",
        "run",
        "uvicorn",
        "weather.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000"
      ]
volumes:
  sqlite_data:
  uploads_data: